### ISSUE TITLE
Hello from the author of Bearded Theme

### ISSUE THREAD

**Issue by BeardedBear** [daomtthuan/visual-studio-bearded-theme#1]
Hello I am the author of Bearded Theme, I receive issues from your port of my version to VSCode, users think I am the author of this port. Could you add "unofficial" either in the name, or on the icon (or both) of your port ?  

Link to the issue : https://github.com/BeardedBear/bearded-theme/issues/103

**Comment by daomtthuan** [comment]
Hello, this is my bad! I forgot add "unofficial" in name.
I will do your request.

**Comment by BeardedBear** [comment]
No probs, thanks ;)
